apiVersion: v1
kind: Secret
metadata:
  name: eks-dev-01-kubeconfig
  namespace: crossplane-system
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: eks-dev-01
        cluster:
          server: https://REPLACE_WITH_TARGET_CLUSTER_ENDPOINT
          certificate-authority-data: REPLACE_WITH_BASE64_CA
    users:
      - name: crossplane-platform-admin
        user:
          token: REPLACE_WITH_SHORT_LIVED_OR_SCOPED_TOKEN
    contexts:
      - name: eks-dev-01
        context:
          cluster: eks-dev-01
          user: crossplane-platform-admin
    current-context: eks-dev-01

